spring:
    data.rest.base-path: /api
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/boardsample
        username: uno
        password: q1w2e3r4
    thymeleaf:
        cache: false
    thymeleaf3:
        decoupled-logic: true
    mvc:
        static-path-pattern: /static/**
    web:
        resources:
            add-mappings: true
            static-locations: classpath:/static